### ISSUE TITLE
Support for `boolean` fields

### ISSUE THREAD

**Issue by xoen** [ministryofjustice/hmpps-digital-prison-reporting-lib#111]
Hello,

I've tried to add a `boolean` field but [it doesn't seem to be supported at the moment](https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/blob/42261914fdde20d135bd2accb781436a3714f104/src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/ParameterType.kt).

This seems to contradict the [list of supported types](https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/blob/42261914fdde20d135bd2accb781436a3714f104/src/main/resources/data-product-definition-schema.json#L98) in the definition schema - unless I'm looking at an unrelated file of course.

At the moment I'm using a `string` type, but filtering doesn't seem to work (I'm still playing with it so there may be a workaround)

**Comment by xoen** [comment]
Update: The workaround I'm using to make filtering work for boolean fields is to convert these columns to text, e.g.

```
      [...]
      "query": "SELECT [...], TEXT(na.is_closed) AS is_closed, [...]
```

**Comment by gavriil-g-moj** [comment]
Boolean fields are now supported since version 3.7.0
There are the relevant changes:
https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/commit/be419a71abe4cb3650d862ecbc4f8b2aad10c09b

**Comment by xoen** [comment]
Ah, interesting, I may have a play with this later, thanks @gavriil-g-moj ☺️

**Comment by xoen** [comment]
Hi @gavriil-g-moj,

I've played with the boolean field for a few minutes and I can confirm the type itself is supported.

**However, filtering doesn't seem to work**. I tried a couple of things in the `filter` section but no dice. The problem seems to be with the generated SQL query adding `lower(is_closed)` on the boolean field which doesn't work (but again as usual, it may be something wrong with my `definitions.json`!)

**Changes**
I've updated the SQL query to remove the conversion to TEXT:

```
SELECT [...], na.is_closed AS is_closed,
[...]
```

Changed the is_closed field to be a `boolean`:
```
[...]
          {
            "name": "is_closed",
            "type": "boolean"
          },
[...]
```

and this is the filter that I had:

```
[...]
          {
            "name": "$ref:is_closed",
            "display": "Closed non-association?",
            "sortable": true,
            "filter": {
              "type": "Radio",
              "default": "false",
              "staticoptions": [
                {
                  "name": "false",
                  "display": "Only open"
                },
                {
                  "name": "true",
                  "display": "Only closed"
                }
              ]
            }
          },
[...]
```

I also tried to change the default/name to `true`/`false` but that didn't change the outcome.

**Errors**

This is what I get while trying to get the default report (tried to add newlines for readability):

```
Database query: 
WITH dataset_ AS (SELECT na.first_prisoner_number,
                         na.first_prisoner_role,
                         na.second_prisoner_number,
                         na.second_prisoner_role,
                         na.reason,
                         na.restriction_type,
                         na.when_created AS created_date,
                         na.when_updated AS updated_date,
                         na.is_closed    AS is_closed,
                         na.closed_at    AS closed_date
                  FROM non_association AS na
                  ORDER BY na.when_created DESC),
     policy_ AS (SELECT * FROM dataset_ WHERE TRUE),
     filter_ AS (SELECT *
                 FROM policy_
                 WHERE created_date >= CAST(:created_date.start AS timestamp)
                   AND created_date < (CAST(:created_date.end AS timestamp) + INTERVAL '1' day)
                   AND lower(is_closed) = :is_closed)
SELECT *
FROM filter_
ORDER BY reason asc
limit 20 OFFSET (1 - 1) * 20;
| userId=A[...]
```

**NOTE**: Notice the offending `lower(is_closed) = :is_closed)` which is the cause of the problem.

And this is an excerpt of the stacktrace (I'll spare you most of the noise):

```
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [WITH dataset_ AS (SELECT na.first_prisoner_number, na.first_prisoner_role, na.second_prisoner_number, na.second_prisoner_role, na.reason, na.restriction_type, na.when_created AS created_date, na.when_updated AS updated_date, na.is_closed AS is_closed, na.closed_at AS closed_date FROM non_association AS na ORDER BY na.when_created DESC),policy_ AS (SELECT * FROM dataset_ WHERE TRUE),filter_ AS (SELECT * FROM policy_ WHERE created_date >= CAST(? AS timestamp) AND created_date < (CAST(? AS timestamp) + INTERVAL '1' day) AND lower(is_closed) = ?)
SELECT COUNT(1) as total FROM filter_]
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:112)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:107)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:116)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1548)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:677)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:723)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:748)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:804)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:218)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForList(NamedParameterJdbcTemplate.java:312)
	at uk.gov.justice.digital.hmpps.digitalprisonreportinglib.data.ConfiguredApiRepository.count(ConfiguredApiRepository.kt:115)
	at uk.gov.justice.digital.hmpps.digitalprisonreportinglib.service.ConfiguredApiService.validateAndCount(ConfiguredApiService.kt:101)
	at uk.gov.justice.digital.hmpps.digitalprisonreportinglib.controller.ConfiguredApiController.configuredApiCount(ConfiguredApiController.kt:235)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[...]
Caused by: org.postgresql.util.PSQLException: ERROR: function lower(boolean) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 530
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[...]
```

**NOTE**: Note the hint: `ERROR: function lower(boolean) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.`

I'm not sure why/who is adding `lower()` on that field (I'm guessing is the DPR library) but maybe that can be tweaked to work with boolean fields.

Hope the above makes sense/is useful but if you have question let me know ☺️

**Comment by gavriil-g-moj** [comment]
Thank you very much Aldo for the very detailed description of this bug.
Lowercasing is added by the backend reporting library and this has been done to allow for more flexibility when filtering and try to prevent user typos. 
I will create a ticket and look into this issue.

**Comment by gavriil-g-moj** [comment]
https://dsdmoj.atlassian.net/browse/DPR2-518 has been created to address this.

**Comment by gavriil-g-moj** [comment]
This has now been fixed in version 3.7.2.
https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/pull/126

**Comment by gavriil-g-moj** [comment]
@xoen could you please test again and let me know if boolean filtering works now.

**Comment by xoen** [comment]
Hi @gavriil-g-moj [I've made these changes](https://github.com/ministryofjustice/hmpps-non-associations-api/pull/250/files) and tested this locally and it works great, thanks again for improving the library ❤️
