### ISSUE TITLE
`format_date()` not working for nullable datetimes

### ISSUE THREAD

**Issue by xoen** [ministryofjustice/hmpps-digital-prison-reporting-lib#122]
Hello, 

I'm using the latest version of the library (`uk.gov.justice.service.hmpps:hmpps-digital-prison-reporting-lib:3.5.2`) and trying to use the `format_date()` formula.

I had to tweak the query to remove the `DATE` conversion for these fields but once I've done that `format_date()` seems to work fine on datetimes when they're present 🎊 

However one of our fields/columns can be null. Before the use of `format_date()` nothing was shown in the table (which is fair enough). Now it errors out for this field when trying to parse the date (which is null).

```
          [... this is the report field]
          {
            "name": "$ref:closed_date",
            "display": "Close Date",
            "formula" : "format_date(${closed_date}, 'dd/MM/yyyy')",
            "sortable": true,
            "defaultsort": false
          }
```

Error:

```
java.time.format.DateTimeParseException: Text '' could not be parsed at index 0
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2108)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:2010)
	at java.base/java.time.LocalDateTime.parse(LocalDateTime.java:494)
	at java.base/java.time.LocalDateTime.parse(LocalDateTime.java:479)
	at uk.gov.justice.digital.hmpps.digitalprisonreportinglib.service.FormulaEngine.interpolateFormatDateFormula(FormulaEngine.kt:45)
	at uk.gov.justice.digital.hmpps.digitalprisonreportinglib.service.FormulaEngine.interpolate(FormulaEngine.kt:36)
	at uk.gov.justice.digital.hmpps.digitalprisonreportinglib.service.FormulaEngine.constructValueWithFormulaInterpolationIfNeeded(FormulaEngine.kt:25)
	at uk.gov.justice.digital.hmpps.digitalprisonreportinglib.service.FormulaEngine.applyFormulas(FormulaEngine.kt:16)
	at uk.gov.justice.digital.hmpps.digitalprisonreportinglib.service.ConfiguredApiService.validateAndFetchData(ConfiguredApiService.kt:69)
	at uk.gov.justice.digital.hmpps.digitalprisonreportinglib.service.ConfiguredApiService.validateAndFetchData$default(ConfiguredApiService.kt:38)
	at uk.gov.justice.digital.hmpps.digitalprisonreportinglib.controller.ConfiguredApiController.configuredApiDataset(ConfiguredApiController.kt:93)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[...more stacktrace, probably not relevant]
```
 
PS: Thanks for implementing the formulas :)

**Comment by gavriil-g-moj** [comment]
Thanks for raising this, we will look into it.
The following ticket has been created:
https://dsdmoj.atlassian.net/browse/DPR2-517

**Comment by gavriil-g-moj** [comment]
This has now been fixed as part of version 3.7.1

**Comment by xoen** [comment]
Thanks @gavriil-g-moj, I may have a play at it later if I get the time :)

**Comment by xoen** [comment]
I can confirm this is also fixed now ❤️
